name: EasyShop
main: com.pixelserver.easyshop.EasyShopPlugin
version: 0.1.0
authors: [PixelServer]
api-version: '1.21'
folia-supported: true
softdepend: [Vault, PlaceholderAPI]
commands:
  easyshop:
    description: EasyShop main command
    usage: /easyshop <reload|shop|market|sell|menu>
    aliases: [eshop]
permissions:
  easyshop.reload:
    default: op
  easyshop.market.sell:
    default: true
  easyshop.market.buy:
    default: true
  easyshop.shop.default:
    default: true
  easyshop.menu.main:
    default: true
