name: ErrorShop
main: com.pixelserver.errorshop.ErrorShopPlugin
version: 0.14
authors: [PixelServer]
api-version: '1.21'
folia-supported: true
softdepend: [Vault, PlaceholderAPI]
commands:
  errorshop:
    description: ErrorShop main command
    usage: /errorshop <reload|shop|market|sell|menu>
    aliases: [eshop]
permissions:
  errorshop.reload:
    default: op
  errorshop.market.sell:
    default: true
  errorshop.market.buy:
    default: true
  errorshop.shop.default:
    default: true
  errorshop.menu.main:
    default: true

softdepend: [Vault, PlayerPoints]
